# Generated by Django 5.2.14 on 2026-05-23 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0002_update_appuser_local_auth'),
    ]

    operations = [
        migrations.CreateModel(
            name='AggregatedMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('survey', 'Survey'), ('campaign', 'Campaign'), ('engagement', 'Engagement'), ('dashboard', 'Dashboard')], default='survey', max_length=50)),
                ('entity_id', models.PositiveIntegerField(help_text='Primary key of the related survey or campaign.')),
                ('metric_name', models.CharField(help_text="Identifier for the metric (e.g. 'total_responses').", max_length=100)),
                ('metric_value', models.FloatField(default=0.0)),
                ('bucket_date', models.DateField(blank=True, help_text='Date bucket for time-series aggregation (daily granularity).', null=True)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aggregated_metrics', to='authentication.appuser')),
            ],
            options={
                'db_table': 'analytics_aggregated_metrics',
                'ordering': ['-computed_at'],
                'indexes': [models.Index(fields=['entity_type', 'entity_id'], name='analytics_a_entity__48db1b_idx'), models.Index(fields=['owner'], name='analytics_a_owner_i_6b864f_idx'), models.Index(fields=['metric_name'], name='analytics_a_metric__74b29b_idx'), models.Index(fields=['bucket_date'], name='analytics_a_bucket__d45955_idx')],
            },
        ),
        migrations.CreateModel(
            name='AnalyticsSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_type', models.CharField(choices=[('survey', 'Survey'), ('campaign', 'Campaign'), ('engagement', 'Engagement'), ('dashboard', 'Dashboard')], db_index=True, default='survey', max_length=50)),
                ('entity_id', models.PositiveIntegerField(blank=True, help_text='PK of the related entity. Null for user-wide snapshots.', null=True)),
                ('payload', models.JSONField(default=dict, help_text='Serialized analytics payload ready for dashboard consumption.')),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_snapshots', to='authentication.appuser')),
            ],
            options={
                'db_table': 'analytics_snapshots',
                'ordering': ['-computed_at'],
                'indexes': [models.Index(fields=['owner', 'snapshot_type'], name='analytics_s_owner_i_2f88da_idx'), models.Index(fields=['entity_id'], name='analytics_s_entity__b1d996_idx'), models.Index(fields=['computed_at'], name='analytics_s_compute_648b4b_idx')],
            },
        ),
        migrations.CreateModel(
            name='MetricCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache_key', models.CharField(db_index=True, help_text="Namespaced cache key (e.g. 'analytics:dashboard:42').", max_length=255, unique=True)),
                ('payload', models.JSONField(default=dict, help_text='Serialized cached payload.')),
                ('expires_at', models.DateTimeField(help_text='When this cache entry expires.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metric_caches', to='authentication.appuser')),
            ],
            options={
                'db_table': 'analytics_metric_cache',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['expires_at'], name='analytics_m_expires_81a65c_idx')],
            },
        ),
    ]
