# Generated by Django 5.2.14 on 2026-05-23 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("email_campaigns", "0002_background_job"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="backgroundjob",
            new_name="email_campa_task_id_b8dae7_idx",
            old_name="ec_bgjob_task_status_idx",
        ),
        migrations.RenameIndex(
            model_name="backgroundjob",
            new_name="email_campa_status_f940e1_idx",
            old_name="ec_bgjob_status_created_idx",
        ),
        migrations.RenameIndex(
            model_name="deliverylog",
            new_name="email_deliv_campaig_2a60fe_idx",
            old_name="email_deliv_campaig_idx",
        ),
        migrations.RenameIndex(
            model_name="deliverylog",
            new_name="email_deliv_status_ea9402_idx",
            old_name="email_deliv_status_idx",
        ),
        migrations.RenameIndex(
            model_name="deliverylog",
            new_name="email_deliv_recipie_179d76_idx",
            old_name="email_deliv_recipie_idx",
        ),
        migrations.RenameIndex(
            model_name="deliverylog",
            new_name="email_deliv_sent_at_25abb7_idx",
            old_name="email_deliv_sent_at_idx",
        ),
    ]
