# Generated by Django 5.2.14 on 2026-05-23 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0003_campaign_email_fields"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="recipient",
            new_name="recipients_audienc_8a197c_idx",
            old_name="recipients_audience_idx",
        ),
        migrations.AlterField(
            model_name="campaign",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("scheduled", "Scheduled"),
                    ("active", "Active"),
                    ("completed", "Completed"),
                    ("archived", "Archived"),
                    ("sending", "Sending"),
                    ("sent", "Sent"),
                    ("failed", "Failed"),
                ],
                default="draft",
                max_length=50,
            ),
        ),
    ]
