AUTOMATION_STATUS_SCHEDULED = "scheduled"
AUTOMATION_STATUS_RUNNING = "running"
AUTOMATION_STATUS_COMPLETED = "completed"
AUTOMATION_STATUS_FAILED = "failed"
AUTOMATION_STATUS_CANCELLED = "cancelled"

AUTOMATION_STATUS_CHOICES = [
    (AUTOMATION_STATUS_SCHEDULED, "Scheduled"),
    (AUTOMATION_STATUS_RUNNING, "Running"),
    (AUTOMATION_STATUS_COMPLETED, "Completed"),
    (AUTOMATION_STATUS_FAILED, "Failed"),
    (AUTOMATION_STATUS_CANCELLED, "Cancelled"),
]

AUTOMATION_TYPE_SCHEDULED_CAMPAIGN = "scheduled_campaign"
AUTOMATION_TYPE_REMINDER = "reminder"

AUTOMATION_TYPE_CHOICES = [
    (AUTOMATION_TYPE_SCHEDULED_CAMPAIGN, "Scheduled Campaign"),
    (AUTOMATION_TYPE_REMINDER, "Reminder"),
]

REMINDER_DELAY_CHOICES = [
    (1, "1 day"),
    (3, "3 days"),
    (7, "7 days"),
]

REMINDER_TYPE_FRIENDLY = "friendly"
REMINDER_TYPE_FINAL = "final"
REMINDER_TYPE_CONVERSATIONAL = "conversational"

REMINDER_TYPE_CHOICES = [
    (REMINDER_TYPE_FRIENDLY, "Friendly Reminder"),
    (REMINDER_TYPE_FINAL, "Final Reminder"),
    (REMINDER_TYPE_CONVERSATIONAL, "Conversational Reminder"),
]

AUTOMATION_EVENT_SCHEDULED = "scheduled"
AUTOMATION_EVENT_STARTED = "started"
AUTOMATION_EVENT_COMPLETED = "completed"
AUTOMATION_EVENT_FAILED = "failed"
AUTOMATION_EVENT_CANCELLED = "cancelled"
AUTOMATION_EVENT_REMINDER_SENT = "reminder_sent"
AUTOMATION_EVENT_REMINDER_SKIPPED = "reminder_skipped"

AUTOMATION_EVENT_CHOICES = [
    (AUTOMATION_EVENT_SCHEDULED, "Scheduled"),
    (AUTOMATION_EVENT_STARTED, "Started"),
    (AUTOMATION_EVENT_COMPLETED, "Completed"),
    (AUTOMATION_EVENT_FAILED, "Failed"),
    (AUTOMATION_EVENT_CANCELLED, "Cancelled"),
    (AUTOMATION_EVENT_REMINDER_SENT, "Reminder Sent"),
    (AUTOMATION_EVENT_REMINDER_SKIPPED, "Reminder Skipped"),
]

TRIGGER_TASK_EXECUTE_SCHEDULED_CAMPAIGN = "execute-scheduled-campaign"
TRIGGER_TASK_PROCESS_REMINDERS = "process-reminders"
TRIGGER_TASK_EVALUATE_FOLLOWUPS = "evaluate-followups"

