# Generated by Django 5.2.14 on 2026-05-23 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("authentication", "0002_update_appuser_local_auth"),
        ("surveys", "0002_survey_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="SimulationConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("config_name", models.CharField(max_length=255)),
                ("is_enabled", models.BooleanField(default=True)),
                ("max_responses", models.PositiveIntegerField(default=10000)),
                ("max_ai_jobs", models.PositiveIntegerField(default=25)),
                ("max_runtime_minutes", models.PositiveIntegerField(default=60)),
                ("max_concurrent_runs", models.PositiveIntegerField(default=2)),
                ("allow_external_api", models.BooleanField(default=False)),
                ("is_simulated", models.BooleanField(default=True, editable=False)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="simulation_configs",
                        to="authentication.appuser",
                    ),
                ),
                (
                    "survey",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="simulation_configs",
                        to="surveys.survey",
                    ),
                ),
            ],
            options={
                "db_table": "simulation_configs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SimulationRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("run_name", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("blocked", "Blocked"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("requested_responses", models.PositiveIntegerField(default=0)),
                ("ai_job_limit", models.PositiveIntegerField(default=0)),
                ("runtime_limit_minutes", models.PositiveIntegerField(default=60)),
                ("allow_external_api", models.BooleanField(default=False)),
                ("is_simulated", models.BooleanField(default=True, editable=False)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("error_message", models.TextField(blank=True, default="")),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "config",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="runs",
                        to="simulation.simulationconfig",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="simulation_runs",
                        to="authentication.appuser",
                    ),
                ),
                (
                    "survey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="simulation_runs",
                        to="surveys.survey",
                    ),
                ),
            ],
            options={
                "db_table": "simulation_runs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SimulationEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("simulation_created", "Simulation Created"),
                            ("simulation_validated", "Simulation Validated"),
                            ("simulation_executed", "Simulation Executed"),
                            ("simulation_blocked", "Simulation Blocked"),
                            ("simulation_cleanup", "Simulation Cleanup"),
                        ],
                        db_index=True,
                        default="simulation_created",
                        max_length=80,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("blocked", "Blocked"),
                            ("info", "Info"),
                        ],
                        db_index=True,
                        default="info",
                        max_length=20,
                    ),
                ),
                ("message", models.TextField(blank=True, default="")),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("is_simulated", models.BooleanField(default=True, editable=False)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="simulation_audit_events",
                        to="authentication.appuser",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="simulation_events",
                        to="authentication.appuser",
                    ),
                ),
                (
                    "simulation_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="simulation.simulationrun",
                    ),
                ),
            ],
            options={
                "db_table": "simulation_events",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="SyntheticDataset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("dataset_name", models.CharField(max_length=255)),
                (
                    "dataset_type",
                    models.CharField(
                        choices=[
                            ("synthetic_response", "Synthetic Response"),
                            ("simulation_analytics", "Simulation Analytics"),
                            ("simulation_ai_output", "Simulation AI Output"),
                        ],
                        db_index=True,
                        default="synthetic_response",
                        max_length=80,
                    ),
                ),
                (
                    "generated_by",
                    models.CharField(
                        choices=[
                            ("ai", "AI"),
                            ("manual", "Manual"),
                            ("system", "System"),
                        ],
                        default="system",
                        max_length=20,
                    ),
                ),
                ("is_simulated", models.BooleanField(default=True, editable=False)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="synthetic_datasets",
                        to="authentication.appuser",
                    ),
                ),
                (
                    "simulation_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="synthetic_datasets",
                        to="simulation.simulationrun",
                    ),
                ),
            ],
            options={
                "db_table": "synthetic_datasets",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="simulationconfig",
            index=models.Index(
                fields=["owner", "is_enabled"], name="simulation__owner_i_405b6e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="simulationconfig",
            index=models.Index(
                fields=["survey"], name="simulation__survey__4ddc2f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="simulationconfig",
            index=models.Index(
                fields=["is_simulated"], name="simulation__is_simu_86054c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="simulationrun",
            index=models.Index(
                fields=["owner", "status"], name="simulation__owner_i_4890cc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="simulationrun",
            index=models.Index(
                fields=["survey", "status"], name="simulation__survey__2860ad_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="simulationrun",
            index=models.Index(
                fields=["is_simulated"], name="simulation__is_simu_c2f2e8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="simulationrun",
            index=models.Index(
                fields=["created_at"], name="simulation__created_efe548_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="simulationevent",
            index=models.Index(
                fields=["simulation_run", "timestamp"],
                name="simulation__simulat_b3e7d8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="simulationevent",
            index=models.Index(
                fields=["owner", "timestamp"], name="simulation__owner_i_d5bb77_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="simulationevent",
            index=models.Index(
                fields=["action_type", "status"], name="simulation__action__a0b581_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="simulationevent",
            index=models.Index(
                fields=["is_simulated"], name="simulation__is_simu_9f8d3f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="syntheticdataset",
            index=models.Index(
                fields=["simulation_run", "dataset_type"],
                name="synthetic_d_simulat_e8b006_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="syntheticdataset",
            index=models.Index(
                fields=["owner", "created_at"], name="synthetic_d_owner_i_97c3af_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="syntheticdataset",
            index=models.Index(
                fields=["is_simulated"], name="synthetic_d_is_simu_440117_idx"
            ),
        ),
    ]
