SIMULATION_RUN_STATUS_PENDING = "pending"
SIMULATION_RUN_STATUS_RUNNING = "running"
SIMULATION_RUN_STATUS_COMPLETED = "completed"
SIMULATION_RUN_STATUS_FAILED = "failed"
SIMULATION_RUN_STATUS_BLOCKED = "blocked"
SIMULATION_RUN_STATUS_ARCHIVED = "archived"

SIMULATION_RUN_STATUS_CHOICES = [
    (SIMULATION_RUN_STATUS_PENDING, "Pending"),
    (SIMULATION_RUN_STATUS_RUNNING, "Running"),
    (SIMULATION_RUN_STATUS_COMPLETED, "Completed"),
    (SIMULATION_RUN_STATUS_FAILED, "Failed"),
    (SIMULATION_RUN_STATUS_BLOCKED, "Blocked"),
    (SIMULATION_RUN_STATUS_ARCHIVED, "Archived"),
]

DATASET_TYPE_RESPONSE = "synthetic_response"
DATASET_TYPE_ANALYTICS = "simulation_analytics"
DATASET_TYPE_AI_OUTPUT = "simulation_ai_output"

DATASET_TYPE_CHOICES = [
    (DATASET_TYPE_RESPONSE, "Synthetic Response"),
    (DATASET_TYPE_ANALYTICS, "Simulation Analytics"),
    (DATASET_TYPE_AI_OUTPUT, "Simulation AI Output"),
]

GENERATED_BY_AI = "ai"
GENERATED_BY_MANUAL = "manual"
GENERATED_BY_SYSTEM = "system"

GENERATED_BY_CHOICES = [
    (GENERATED_BY_AI, "AI"),
    (GENERATED_BY_MANUAL, "Manual"),
    (GENERATED_BY_SYSTEM, "System"),
]

SIMULATION_ACTION_CREATED = "simulation_created"
SIMULATION_ACTION_VALIDATED = "simulation_validated"
SIMULATION_ACTION_EXECUTED = "simulation_executed"
SIMULATION_ACTION_BLOCKED = "simulation_blocked"
SIMULATION_ACTION_CLEANUP = "simulation_cleanup"

SIMULATION_ACTION_CHOICES = [
    (SIMULATION_ACTION_CREATED, "Simulation Created"),
    (SIMULATION_ACTION_VALIDATED, "Simulation Validated"),
    (SIMULATION_ACTION_EXECUTED, "Simulation Executed"),
    (SIMULATION_ACTION_BLOCKED, "Simulation Blocked"),
    (SIMULATION_ACTION_CLEANUP, "Simulation Cleanup"),
]

SIMULATION_EVENT_STATUS_SUCCESS = "success"
SIMULATION_EVENT_STATUS_FAILED = "failed"
SIMULATION_EVENT_STATUS_BLOCKED = "blocked"
SIMULATION_EVENT_STATUS_INFO = "info"

SIMULATION_EVENT_STATUS_CHOICES = [
    (SIMULATION_EVENT_STATUS_SUCCESS, "Success"),
    (SIMULATION_EVENT_STATUS_FAILED, "Failed"),
    (SIMULATION_EVENT_STATUS_BLOCKED, "Blocked"),
    (SIMULATION_EVENT_STATUS_INFO, "Info"),
]

