# Generated by Django 5.2.14 on 2026-05-23 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AIJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("text_analysis", "Text Analysis"),
                            ("summarization", "Summarization"),
                            ("classification", "Classification"),
                            ("recommendation", "Recommendation"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("result", models.JSONField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, default="")),
            ],
            options={
                "db_table": "ai_jobs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "created_at"],
                        name="ai_jobs_status_fe84a1_idx",
                    ),
                    models.Index(
                        fields=["job_type", "status"], name="ai_jobs_job_typ_028e95_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AIPromptTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(db_index=True, max_length=100, unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("survey_analysis", "Survey Analysis"),
                            ("summarization", "Summarization"),
                            ("classification", "Classification"),
                            ("recommendation", "Recommendation"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("system_context", models.TextField()),
                ("user_context_template", models.TextField()),
                ("task_instructions", models.TextField()),
                ("output_constraints", models.TextField(blank=True, default="")),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("version", models.PositiveSmallIntegerField(default=1)),
            ],
            options={
                "db_table": "ai_prompt_templates",
                "ordering": ["category", "name"],
                "indexes": [
                    models.Index(
                        fields=["category", "is_active"],
                        name="ai_prompt_t_categor_58bb4a_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AIExecution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "model_name",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("prompt_preview", models.TextField(blank=True, default="")),
                ("raw_response", models.TextField(blank=True, default="")),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("attempt_number", models.PositiveSmallIntegerField(default=1)),
                ("success", models.BooleanField(default=False)),
                ("error_message", models.TextField(blank=True, default="")),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executions",
                        to="ai.aijob",
                    ),
                ),
            ],
            options={
                "db_table": "ai_executions",
                "ordering": ["attempt_number"],
                "indexes": [
                    models.Index(
                        fields=["job", "attempt_number"],
                        name="ai_executio_job_id_f5fceb_idx",
                    ),
                    models.Index(
                        fields=["success"], name="ai_executio_success_ee0e15_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AIUsageRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("model_name", models.CharField(db_index=True, max_length=100)),
                ("tokens_used", models.PositiveIntegerField(default=0)),
                ("request_type", models.CharField(db_index=True, max_length=50)),
                ("execution_time", models.FloatField(default=0.0)),
                (
                    "estimated_cost",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=10, null=True
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="usage_records",
                        to="ai.aijob",
                    ),
                ),
            ],
            options={
                "db_table": "ai_usage_records",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["model_name", "created_at"],
                        name="ai_usage_re_model_n_75781b_idx",
                    ),
                    models.Index(
                        fields=["request_type", "created_at"],
                        name="ai_usage_re_request_237e83_idx",
                    ),
                ],
            },
        ),
    ]
