CAMPAIGN_STATUS_DRAFT = "draft"
CAMPAIGN_STATUS_SCHEDULED = "scheduled"
CAMPAIGN_STATUS_ACTIVE = "active"
CAMPAIGN_STATUS_COMPLETED = "completed"
CAMPAIGN_STATUS_ARCHIVED = "archived"

CAMPAIGN_STATUS_CHOICES = [
    (CAMPAIGN_STATUS_DRAFT, "Draft"),
    (CAMPAIGN_STATUS_SCHEDULED, "Scheduled"),
    (CAMPAIGN_STATUS_ACTIVE, "Active"),
    (CAMPAIGN_STATUS_COMPLETED, "Completed"),
    (CAMPAIGN_STATUS_ARCHIVED, "Archived"),
]

VALID_TRANSITIONS = {
    CAMPAIGN_STATUS_DRAFT: {CAMPAIGN_STATUS_SCHEDULED, CAMPAIGN_STATUS_ARCHIVED},
    CAMPAIGN_STATUS_SCHEDULED: {CAMPAIGN_STATUS_ACTIVE, CAMPAIGN_STATUS_DRAFT},
    CAMPAIGN_STATUS_ACTIVE: {CAMPAIGN_STATUS_COMPLETED},
    CAMPAIGN_STATUS_COMPLETED: {CAMPAIGN_STATUS_ARCHIVED},
    CAMPAIGN_STATUS_ARCHIVED: set(),
}
