# Email template identifiers (used by Campaign.template_name)
TEMPLATE_SURVEY_INVITATION = "survey_invitation"
TEMPLATE_REMINDER = "reminder_email"
TEMPLATE_TEST = "test_email"

TEMPLATE_CHOICES = [
    (TEMPLATE_SURVEY_INVITATION, "Survey Invitation"),
    (TEMPLATE_REMINDER, "Reminder Email"),
    (TEMPLATE_TEST, "Test Email"),
]

CAMPAIGN_STATUS_DRAFT = "draft"
CAMPAIGN_STATUS_SCHEDULED = "scheduled"
CAMPAIGN_STATUS_ACTIVE = "active"
CAMPAIGN_STATUS_COMPLETED = "completed"
CAMPAIGN_STATUS_ARCHIVED = "archived"

# Email delivery lifecycle statuses
CAMPAIGN_STATUS_SENDING = "sending"
CAMPAIGN_STATUS_SENT = "sent"
CAMPAIGN_STATUS_FAILED = "failed"

CAMPAIGN_STATUS_CHOICES = [
    (CAMPAIGN_STATUS_DRAFT, "Draft"),
    (CAMPAIGN_STATUS_SCHEDULED, "Scheduled"),
    (CAMPAIGN_STATUS_ACTIVE, "Active"),
    (CAMPAIGN_STATUS_COMPLETED, "Completed"),
    (CAMPAIGN_STATUS_ARCHIVED, "Archived"),
    (CAMPAIGN_STATUS_SENDING, "Sending"),
    (CAMPAIGN_STATUS_SENT, "Sent"),
    (CAMPAIGN_STATUS_FAILED, "Failed"),
]

VALID_TRANSITIONS = {
    CAMPAIGN_STATUS_DRAFT: {
        CAMPAIGN_STATUS_SCHEDULED,
        CAMPAIGN_STATUS_ARCHIVED,
        CAMPAIGN_STATUS_SENDING,
    },
    CAMPAIGN_STATUS_SCHEDULED: {CAMPAIGN_STATUS_ACTIVE, CAMPAIGN_STATUS_DRAFT},
    CAMPAIGN_STATUS_ACTIVE: {CAMPAIGN_STATUS_COMPLETED},
    CAMPAIGN_STATUS_COMPLETED: {CAMPAIGN_STATUS_ARCHIVED},
    CAMPAIGN_STATUS_ARCHIVED: set(),
    CAMPAIGN_STATUS_SENDING: {CAMPAIGN_STATUS_SENT, CAMPAIGN_STATUS_FAILED},
    CAMPAIGN_STATUS_SENT: set(),
    CAMPAIGN_STATUS_FAILED: {CAMPAIGN_STATUS_DRAFT},
}
