# Generated by Django 5.2.14 on 2026-05-23 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("automation", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="automationevent",
            new_name="automation__schedul_5d6c57_idx",
            old_name="automation__schedul_evt_idx",
        ),
        migrations.RenameIndex(
            model_name="automationevent",
            new_name="automation__campaig_f1cd2f_idx",
            old_name="automation__campaig_evt_idx",
        ),
        migrations.RenameIndex(
            model_name="automationevent",
            new_name="automation__owner_i_d887b0_idx",
            old_name="automation__owner_e_idx",
        ),
        migrations.RenameIndex(
            model_name="automationevent",
            new_name="automation__event_t_8c0e5c_idx",
            old_name="automation__event_t_idx",
        ),
        migrations.RenameIndex(
            model_name="automationevent",
            new_name="automation__recipie_bcc5e0_idx",
            old_name="automation__recipie_idx",
        ),
        migrations.RenameIndex(
            model_name="automationevent",
            new_name="automation__created_b92393_idx",
            old_name="automation__created_idx",
        ),
        migrations.RenameIndex(
            model_name="automationschedule",
            new_name="automation__campaig_8ac231_idx",
            old_name="automation__campaig_idx",
        ),
        migrations.RenameIndex(
            model_name="automationschedule",
            new_name="automation__owner_i_2e2fec_idx",
            old_name="automation__owner_i_idx",
        ),
        migrations.RenameIndex(
            model_name="automationschedule",
            new_name="automation__status_7e8fe4_idx",
            old_name="automation__status_idx",
        ),
        migrations.RenameIndex(
            model_name="automationschedule",
            new_name="automation__schedul_20b625_idx",
            old_name="automation__schedul_idx",
        ),
        migrations.RenameIndex(
            model_name="automationschedule",
            new_name="automation__automat_b54ba3_idx",
            old_name="automation__automat_idx",
        ),
        migrations.RenameIndex(
            model_name="reminderrule",
            new_name="reminder_ru_campaig_f8e539_idx",
            old_name="reminder_ru_campaig_idx",
        ),
        migrations.RenameIndex(
            model_name="reminderrule",
            new_name="reminder_ru_owner_i_136261_idx",
            old_name="reminder_ru_owner_i_idx",
        ),
        migrations.RenameIndex(
            model_name="reminderrule",
            new_name="reminder_ru_delay_d_33e032_idx",
            old_name="reminder_ru_delay_d_idx",
        ),
        migrations.RenameIndex(
            model_name="reminderrule",
            new_name="reminder_ru_is_enab_e26024_idx",
            old_name="reminder_ru_is_enab_idx",
        ),
        migrations.RenameIndex(
            model_name="reminderrule",
            new_name="reminder_ru_recipie_d42112_idx",
            old_name="reminder_ru_recipie_idx",
        ),
    ]
