export const clerkAppearance = {
  variables: {
    colorPrimary: "#3B82F6",
    colorBackground: "#FFFFFF",
    colorInputBackground: "#FFFFFF",
    colorInputText: "#0F172A",
    colorText: "#0F172A",
    colorTextSecondary: "#475569",
    colorTextOnPrimaryBackground: "#FFFFFF",
    colorNeutral: "#94A3B8",
    colorDanger: "#EF4444",
    fontFamily: "'Inter', system-ui, -apple-system, sans-serif",
    fontSize: "14px",
    borderRadius: "6px",
    spacingUnit: "16px",
  },
  elements: {
    rootBox: "w-full",
    card: "shadow-[0_4px_12px_rgba(15,23,42,0.06)] border border-[#E2E8F0] rounded-[14px] w-full",
    headerTitle: "text-[#0F172A] font-bold text-xl",
    headerSubtitle: "text-[#475569] text-sm",
    formButtonPrimary:
      "bg-[#3B82F6] hover:bg-[#2563EB] active:bg-[#1D4ED8] text-white rounded-[10px] font-medium text-sm shadow-none transition-colors",
    formFieldInput:
      "border-[#E2E8F0] rounded-[6px] text-[#0F172A] bg-white text-sm placeholder:text-[#94A3B8] focus:border-[#3B82F6] focus:ring-1 focus:ring-[#3B82F6]",
    formFieldLabel: "text-[#0F172A] font-medium text-sm",
    footerActionLink: "text-[#3B82F6] hover:text-[#2563EB] font-medium",
    footerActionText: "text-[#475569] text-sm",
    dividerLine: "bg-[#E2E8F0]",
    dividerText: "text-[#94A3B8] text-xs",
    socialButtonsBlockButton:
      "border border-[#E2E8F0] text-[#0F172A] hover:bg-[#F5F7FB] rounded-[10px] text-sm font-medium transition-colors",
    socialButtonsBlockButtonText: "text-[#0F172A] font-medium",
    identityPreviewEditButton: "text-[#3B82F6] hover:text-[#2563EB]",
    formFieldSuccessText: "text-[#22C55E] text-xs",
    formFieldErrorText: "text-[#EF4444] text-xs",
    alertText: "text-sm",
    badge: "bg-[#EEF4FF] text-[#2563EB] rounded-full text-xs font-medium",
  },
} as const;
